apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

configMapGenerator:
  - name: restful-app-config
    behavior: replace
    envs:
      - config.env
generatorOptions:
  disableNameSuffixHash: true

patches:
  - path: patch-deployment.yaml
    target:
      kind: Deployment
      name: restful-app
  - path: patch-hpa.yaml
  - path: patch-migration.yaml
