apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

configMapGenerator:
  - name: restful-app-config
    envs:
      - config.env
generatorOptions:
  disableNameSuffixHash: true

patchesStrategicMerge:
  - patch-deployment.yaml
  - patch-hpa.yaml
  - patch-migration.yaml