apiVersion: batch/v1
kind: CronJob
metadata:
  name: restful-app-create-user-job
spec:
  schedule: "0 */1 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 0
  failedJobHistoryLimit: 1
  startingDeadlineSeconds: 3600
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        metadata:
          labels:
            app: restful-app
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          containers:
          - name: restful-app-create-user-job
            image: restful-app
            command:
            - /bin/sh
            resources:
              requests:
                memory: "256Mi"
                cpu: "10m"
              limits:
                memory: "512Mi"
                cpu: "20m"
            securityContext:
              allowPrivilegeEscalation: false
          restartPolicy: OnFailure
