apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: restful-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tuananhhedspibk/restful-app-k8s
    targetRevision: HEAD
    path: overlays/dev
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true