apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patchesStrategicMerge:
- patch-deployment.yaml
- patch-hpa.yaml
images:
- name: restful-app
  newName: 265593583957.dkr.ecr.ap-northeast-1.amazonaws.com/restful-app/restful-app
  newTag: 54821cc03482668f45067f40781f59040cd4874e
