apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- namespace.yaml
- service-account.yaml
- secret-provider-class.yaml
- ingress.yaml

configMapGenerator:
- behavior: replace
  envs:
  - config.env
  name: restful-app-config
generatorOptions:
  disableNameSuffixHash: true

patchesStrategicMerge:
- patch-deployment.yaml
- patch-hpa.yaml
- patch-migration.yaml

namespace: restful-stg
images:
- name: restful-app
  newName: 265593583957.dkr.ecr.ap-northeast-1.amazonaws.com/restful-app
  newTag: 721275e6f6351c3f2ed7d691c31f6a08be7bb39e
