apiVersion: batch/v1
kind: Job
metadata:
  name: restful-app-migration
  labels:
    app: restful-app-migration
spec:
  template:
    spec:
      # serviceAccountName: restful-app-stg-sa
      automountServiceAccountToken: true
      containers:
      - name: restful-app-migration
        command: ["npm", "run", "migration:run"]
        resources:
          requests:
            memory: "256Mi"
            cpu: "10m"
          limits:
            memory: "512Mi"
            cpu: "20m"
        envFrom:
          - configMapRef:
              name: restful-app-config
          - secretRef:
              name: app-secrets
        volumeMounts:
          - mountPath: /secrets
            name: app-secrets
            readOnly: true
      
      volumes:
        - name: app-secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: restful-app-secrets