apiVersion: batch/v1
kind: Job
metadata:
  name: restful-app-migration
  labels:
    app: restful-app-migration
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        app: restful-app-migration
      annotations:
        sidecar.istio.io/inject: "false"
        argocd.argoproj.io/sync-wave: "1"
    spec:
      containers:
      - name: restful-app-migration
        securityContext:
          allowPrivilegeEscalation: false
        envFrom:
          - configMapRef:
              name: restful-app-config
        volumeMounts:
          - mountPath: /secrets
            name: app-secrets
            readOnly: true
        command: ["npm", "run", "migration:run"]
      restartPolicy: Never
      
      volumes:
        - name: app-secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: restful-app-secrets