apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: restful-app-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  provider: aws
  secretObjects:
    - data:
        - key: host
          objectName: database_obj
        - key: port
          objectName: database_obj
        - key: username
          objectName: database_obj
        - key: password
          objectName: database_obj
        - key: name
          objectName: database_obj
      secretName: restful-app-secrets
      type: Opaque
  parameters:
    objects: |
      - objectName: "database"
        objectType: "secretsmanager"
        jmesPath:
          - path: /
            objectAlias: database_obj