apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: restful-app-secrets
spec:
  provider: aws
  secretObjects:
    - data:
        - key: host
          objectName: database_obj
        - key: port
          objectName: database_obj
        - key: username
          objectName: database_obj
        - key: password
          objectName: database_obj
        - key: name
          objectName: database_obj
      secretName: restful-app-secrets
      type: Opaque
  parameters:
    objects: |
      - objectName: ""
        objectType: "secretsmanager"
        jmesPath:
          - path: database
            objectAlias: database_obj