apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: restful-app-secrets
  namespace: restful-stg
spec:
  provider: aws
  parameters:
    region: ap-northeast-1
    objects: |
      - objectName: "database"
        objectType: "secretsmanager"
  secretObjects:
    - secretName: app-secrets
      type: Opaque
      data:
        - objectName: "database"
          key: "DATABASE_HOST
          alias: "DATABASE_HOST
        - objectName: "database"
          key: "DATABASE_PORT"
          alias: "DATABASE_PORT"
        - objectName: "database"
          key: "DATABASE_USERNAME"
          alias: "DATABASE_USERNAME"
        - objectName: "database"
          key: "DATABASE_PASSWORD"
          alias: "DATABASE_PASSWORD"
        - objectName: "database"
          key: "DATABASE_NAME"
          alias: "DATABASE_NAME"
