apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: restful-app-secrets
  namespace: restful-stg
spec:
  provider: aws
  parameters:
    region: ap-northeast-1
    objects: |
      - objectName: "database"
        objectType: "secretsmanager"
        jmesPath:
          - path: DATABASE_HOST
            objectAlias: DATABASE_HOST
          - path: DATABASE_PORT
            objectAlias: DATABASE_PORT
          - path: DATABASE_USERNAME
            objectAlias: DATABASE_USERNAME
          - path: DATABASE_PASSWORD
            objectAlias: DATABASE_PASSWORD
          - path: DATABASE_NAME
            objectAlias: DATABASE_NAME
  secretObjects:
    - secretName: app-secrets
      type: Opaque
      data:
        - objectName: "DATABASE_HOST"
          key: "DATABASE_HOST"
        - objectName: "DATABASE_PORT"
          key: "DATABASE_PORT"
        - objectName: "DATABASE_USERNAME"
          key: "DATABASE_USERNAME"
        - objectName: "DATABASE_PASSWORD"
          key: "DATABASE_PASSWORD"
        - objectName: "DATABASE_NAME"
          key: "DATABASE_NAME"
