apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: restful-app-secrets
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "1"
spec:
  provider: aws
  secretObjects:
    - data:
        - key: DATABASE_HOST
          objectName: database_obj
        - key: DATABASE_PORT
          objectName: database_obj
        - key: DATABASE_USERNAME
          objectName: database_obj
        - key: DATABASE_PASSWORD
          objectName: database_obj
        - key: DATABASE_NAME
          objectName: database_obj
      secretName: restful-app-secrets
      type: Opaque
  parameters:
    region: ap-northeast-1
    objects: |
      - objectName: database
        objectType: secretsmanager
        jmesPath:
          - path: /
            objectAlias: database_obj