apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: restful-app-secrets
  namespace: restful-stg
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "1"
spec:
  provider: aws
  parameters:
    region: ap-northeast-1
    objects: |
      - objectName: "database"
        objectType: "secretsmanager"
        jmesPath:
          - path: host
            objectAlias: DATABASE_HOST
          - path: port
            objectAlias: DATABASE_PORT
          - path: username
            objectAlias: DATABASE_USERNAME
          - path: password
            objectAlias: DATABASE_PASSWORD
          - path: name
            objectAlias: DATABASE_NAME
  secretObjects:
    - secretName: app-secrets
      type: Opaque
      data:
        - objectName: DATABASE_HOST
          key: DATABASE_HOST
        - objectName: DATABASE_PORT
          key: DATABASE_PORT
        - objectName: DATABASE_USERNAME
          key: DATABASE_USERNAME
        - objectName: DATABASE_PASSWORD
          key: DATABASE_PASSWORD
        - objectName: DATABASE_NAME
          key: DATABASE_NAME
