apiVersion: apps/v1
kind: Deployment
metadata:
  name: restful-app
  namespace: default
  labels:
    app: restful-app
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: restful-app
  template:
    metadata:
      labels:
        app: restful-app
    spec:
      containers:
        - name: restful-app
          image: trantuananh/restful-app:latest
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: restful-app-config
          readinessProbe:
            httpGet:
              path: /v1/health
              port: 3000
            periodSeconds: 10
            timeoutSeconds: 15
            successThreshold: 1
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /v1/health
              port: 3000
            periodSeconds: 10
            timeoutSeconds: 15
            successThreshold: 1
            failureThreshold: 5
          startupProbe:
            httpGet:
              path: /v1/health
              port: 3000
            timeoutSeconds: 50
            periodSeconds: 10
            failureThreshold: 100
            initialDelaySeconds: 80
            