resources:
- ./deployment.yaml
- ./service.yaml
- ./hpa.yaml

configMapGenerator:
- name: restful-app-env-variables
generatorOptions:
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "1"
  disableNameSuffixHash: true
