resources:
- ./deployment.yaml
- ./service.yaml
- ./hpa.yaml
- ./migration.yaml

configMapGenerator:
  - name: restful-app-config
  - envs:
    - config.env
generatorOptions:
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "1"
  disableNameSuffixHash: true
