apiVersion: batch/v1
kind: Job
metadata:
  name: restful-app-migration
  labels:
    app: restful-app-migration
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        app: restful-app-migration
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: restful-app-migration
        image: trantuananh/restful-app:latest
        securityContext:
          allowPrivilegeEscalation: false
      restartPolicy: Never