apiVersion: v1
kind: Service
metadata:
  name: restful-app
  namespace: default
spec:
  selector:
    app: restful-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer